### ISSUE TITLE
Medical set

### ISSUE THREAD

**Issue by thebrandonlewis** [Remix-Design/RemixIcon#165] opened 2020-04-01 12:46 UTC
## Icon Request

* Icon name: 
* Tags of this icon: 
* Use case: 
* Screenshots of similar icons:

**Comment by itsezc** [comment] 2020-04-11 11:35
Duplicate of (Issue) https://github.com/Remix-Design/RemixIcon/issues/61

**Closed** 2020-05-23 13:17 UTC
Labels: icon request, in progress
