### ISSUE TITLE
Need Food related icons asap please

### ISSUE THREAD

**Issue by ThantHtetAung101** [Remix-Design/RemixIcon#496] opened 2023-03-07 06:27 UTC
## Icon Request

* Icon name: Food
* Tags of this icon: Idk
* Use case: For Food related websites
* Screenshots of similar icons: dunno

**Comment by itsezc** [comment] 2023-04-03 21:16
Duplicate of #85

**Comment by xiaochunjimmy** [comment] 2023-12-09 12:02
Some food icons have been made.
If there are specific needs, they can be raised.

**Closed** 2024-02-27 07:04 UTC
Labels: icon request, in progress
